In [2]:
import pandas as pd
import numpy as np

In [198]:
df = pd.read_csv('rai_dataset.csv')
df.head()

,casted,convivaSessionId,chipset,bufferStatus,bitRate,startFrameNumber,adOrVideo,deviceDetails,contentID,qualityResolution,...,videoType,freePreview,lastGAEvents,statsforNerd,errorType,packName,playerSource,customLog,timestamp_fe,videoSessionId
0,False,0.0,trinket,-1.0,-1.0,-1.0,NaN,vivo 1935 vivo,1.000106e+09,NaN,...,VOD,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,0.0,sdm845,27.0,5371.0,-1.0,Video,ONEPLUS A6000 OnePlus,1.000228e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,0.0,sdm845,-1.0,-1.0,-1.0,NaN,ONEPLUS A6010 OnePlus,1.000229e+09,NaN,...,LIVE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,0.0,panther,-1.0,-1.0,-1.0,NaN,Pixel 7 Google,1.000229e+09,NaN,...,LIVE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,0.0,Spacewar,94.0,1608.0,136.0,Video,A063 Nothing,1.000229e+09,1280x720,...,LIVE,No,video_stop->video_play_start->video_start,"(14,2.3,88423,1608)",NaN,LIV_Pre_12M,home_masthead_click,NaN,NaN,YWZhNTFjZmI4MDBmZWY5OF8xNjkwNDE3ODEyODY4

In [199]:
df.shape

(3297, 62)

In [200]:
df['date'] = pd.to_datetime(df['timestamp']).dt.date
df['time'] = pd.to_datetime(df['timestamp']).dt.time

In [222]:
date1 = df['date']
time1 = df['time']

In [224]:
df1 = pd.DataFrame({'Date':date1,'Time':time1})
df1

           Date      Time
0    2023-07-26  18:32:14
1    2023-07-26  21:26:32
2    2023-07-27  00:57:39
3    2023-07-27  01:22:25
4    2023-07-27  00:34:54
...         ...       ...
3292 2023-07-27  16:45:22
3293 2023-07-27  06:32:28
3294 2023-07-27  06:33:22
3295 2023-07-27  13:32:28
3296 2023-07-27  08:07:41

[3297 rows x 2 columns]

In [229]:
df['timestamp1']=pd.to_datetime(df1.Date.astype(str)+' '+df1.Time.astype(str))

In [231]:
# df['timestamp1'] = pd.to_datetime(df['date'] + ' ' + df['time'])
df.tail()

,casted,convivaSessionId,chipset,bufferStatus,bitRate,startFrameNumber,adOrVideo,deviceDetails,contentID,qualityResolution,...,statsforNerd,errorType,packName,playerSource,customLog,timestamp_fe,videoSessionId,date,time,timestamp1
3292,NaN,NaN,Mali-450 MP,-1.0,NaN,NaN,video,Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 ...,1.000062e+09,NaN,...,"(0.00 Mbps,0.00 KB,0.00 s,0.00 Kbps)",NaN,JIO_SONYLIV_PREM,home_premium_banner_thumbnail_click,NaN,NaN,NaN,2023-07-27,16:45:22,2023-07-27 16:45:22
3293,False,NaN,Apple GPU,-1.0,NaN,25.0,Video,5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS ...,1.000228e+09,NaN,...,"undefined,undefined,undefined",VIDEO_URL_ERROR,Registered,details screen,NaN,27-7-2023::12:2:16,YmFmMmNmNmJjMDQ4NGYwNTkwOWFiZGRkNmY4OTY3OTYtMT...,2023-07-27,06:32:28,2023-07-27 06:32:28
3294,False,NaN,Apple GPU,-1.0,NaN,25.0,Video,5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS ...,1.000228e+09,NaN,...,"undefined,undefined,undefined",VIDEO_URL_ERROR,Registered,details screen,NaN,27-7-2023::12:3:12,YmFmMmNmNmJjMDQ4NGYwNTkwOWFiZGRkNmY4OTY3OTYtMT...,2023-07-27,06:33:22,2023-07-27 06:33:22
3295,False,NaN,Apple GPU,-1.0,NaN,25.0,Video,5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS ...,1.000228e+09,NaN,...,"undefined,undefined,undefined",VIDEO_URL_ERROR,Registered,details screen,NaN,27-7-2023::19:2:19,NzNmOWU5NjIzN2ViNDY3MDhlMTcyZTZkMTFhYjlmMGItMT...,2023-07-27,13:32:28,2023-07-27 13:32:28
3296,False,NaN,Apple GPU,-1.0,NaN,25.0,Video,5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS ...,1.000228e+09,NaN,...,"undefined,undefined,undefined",VIDEO_URL_ERROR,Registered,deeplink,NaN,27-7-2023::13:37:34,NDgxN2FhMzM4OGY4NDBjZTk0ZGU0NjAzZjgzZmYzZmQtMT...,2023-07-27,08:07:41,2023-07-27 08:07:41

In [232]:
df.to_csv('timestamp1.csv')

In [264]:
# df.inserted_at
# df['Dates_inserted_at'] = pd.to_datetime(df['inserted_at']).dt.date
df['Time_inserted_at'] = pd.to_datetime(df['inserted_at']).dt.time

In [240]:
df.head()

,casted,convivaSessionId,chipset,bufferStatus,bitRate,startFrameNumber,adOrVideo,deviceDetails,contentID,qualityResolution,...,packName,playerSource,customLog,timestamp_fe,videoSessionId,date,time,timestamp1,Dates_inserted_at,Time_inserted_at
0,False,0.0,trinket,-1.0,-1.0,-1.0,NaN,vivo 1935 vivo,1.000106e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-26,18:32:14,2023-07-26 18:32:14,2023-07-27,00:02:14.365154
1,False,0.0,sdm845,27.0,5371.0,-1.0,Video,ONEPLUS A6000 OnePlus,1.000228e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-26,21:26:32,2023-07-26 21:26:32,2023-07-27,02:56:33.212097
2,False,0.0,sdm845,-1.0,-1.0,-1.0,NaN,ONEPLUS A6010 OnePlus,1.000229e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-27,00:57:39,2023-07-27 00:57:39,2023-07-27,06:27:39.935419
3,False,0.0,panther,-1.0,-1.0,-1.0,NaN,Pixel 7 Google,1.000229e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-07-27,01:22:25,2023-07-27 01:22:25,2023-07-27,06:52:25.818630
4,False,0.0,Spacewar,94.0,1608.0,136.0,Video,A063 Nothing,1.000229e+09,1280x720,...,LIV_Pre_12M,home_masthead_click,NaN,NaN,YWZhNTFjZmI4MDBmZWY5OF8xNjkwNDE3ODEyODY4,2023-07-27,00:34:54,2023-07-27 00:34:54,2023-07-27,06:04:55.011682

In [265]:
date2 = df['Dates_inserted_at']
time2 = df['Time_inserted_at']

In [266]:
df2 = pd.DataFrame({'Date':date2,'Time':time2})
df2

            Date             Time
0     2023-07-27  00:02:14.365154
1     2023-07-27  02:56:33.212097
2     2023-07-27  06:27:39.935419
3     2023-07-27  06:52:25.818630
4     2023-07-27  06:04:55.011682
...          ...              ...
3292  2023-07-27  22:15:22.446977
3293  2023-07-27  12:02:28.259608
3294  2023-07-27  12:03:22.720804
3295  2023-07-27  19:02:28.418978
3296  2023-07-27  13:37:42.212386

[3297 rows x 2 columns]

In [267]:
df['inserted_at1']=pd.to_datetime(df2.Date.astype(str)+' '+df2.Time.astype(str))

# df['Dates'] = pd.to_datetime(df['date']).dt.date
# df['Time'] = pd.to_datetime(df['date']).dt.time

In [268]:
df.head()

,casted,convivaSessionId,chipset,bufferStatus,bitRate,startFrameNumber,adOrVideo,deviceDetails,contentID,qualityResolution,...,playerSource,customLog,timestamp_fe,videoSessionId,date,time,timestamp1,Dates_inserted_at,Time_inserted_at,inserted_at1
0,False,0.0,trinket,-1.0,-1.0,-1.0,NaN,vivo 1935 vivo,1.000106e+09,NaN,...,NaN,NaN,NaN,NaN,2023-07-26,18:32:14,2023-07-26 18:32:14,2023-07-27,00:02:14.365154,2023-07-27 00:02:14.365154
1,False,0.0,sdm845,27.0,5371.0,-1.0,Video,ONEPLUS A6000 OnePlus,1.000228e+09,NaN,...,NaN,NaN,NaN,NaN,2023-07-26,21:26:32,2023-07-26 21:26:32,2023-07-27,02:56:33.212097,2023-07-27 02:56:33.212097
2,False,0.0,sdm845,-1.0,-1.0,-1.0,NaN,ONEPLUS A6010 OnePlus,1.000229e+09,NaN,...,NaN,NaN,NaN,NaN,2023-07-27,00:57:39,2023-07-27 00:57:39,2023-07-27,06:27:39.935419,2023-07-27 06:27:39.935419
3,False,0.0,panther,-1.0,-1.0,-1.0,NaN,Pixel 7 Google,1.000229e+09,NaN,...,NaN,NaN,NaN,NaN,2023-07-27,01:22:25,2023-07-27 01:22:25,2023-07-27,06:52:25.818630,2023-07-27 06:52:25.818630
4,False,0.0,Spacewar,94.0,1608.0,136.0,Video,A063 Nothing,1.000229e+09,1280x720,...,home_masthead_click,NaN,NaN,YWZhNTFjZmI4MDBmZWY5OF8xNjkwNDE3ODEyODY4,2023-07-27,00:34:54,2023-07-27 00:34:54,2023-07-27,06:04:55.011682,2023-07-27 06:04:55.011682

In [269]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3297 entries, 0 to 3296
Data columns (total 68 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   casted                   3044 non-null   object
 1   convivaSessionId         2844 non-null   float64
 2   chipset                  3296 non-null   object
 3   bufferStatus             3296 non-null   float64
 4   bitRate                  1347 non-null   float64
 5   startFrameNumber         3104 non-null   float64
 6   adOrVideo                2535 non-null   object
 7   deviceDetails            3296 non-null   object
 8   contentID                3294 non-null   float64
 9   qualityResolution        1578 non-null   object
 10  videoState               3293 non-null   object
 11  downloadBandwidth        3226 non-null   object
 12  appVersion               3296 non-null   object
 13  networkStrength          2472 non-null   object
 14  platform                 3296 non-null   object
 15  OSDetails                3296 non-null   object
 16  deviceScreenResolution   3296 non-null   object
 17  IssueType                3297 non-null   object
 18  orientation              3296 non-null   object
 19  IssueTime                3297 non-null   object
 20  userIdentifier           3290 non-null   object
 21  cdn                      2443 non-null   object
 22  userAgent                2199 non-null   object
 23  errorCode                1716 non-null   object
 24  lastRenderedFrameNumber  3175 non-null   float64
 25  IssueDetails             2151 non-null   object
 26  mode                     3295 non-null   object
 27  emailId                  1186 non-null   object
 28  state                    3296 non-null   object
 29  country                  3296 non-null   object
 30  mobileNumber             2896 non-null   float64
 31  deviceType               3297 non-null   object
 32  inserted_at              3297 non-null   object
 33  cluster                  3297 non-null   object
 34  IP                       3297 non-null   object
 35  appVersionCode           1843 non-null   float64
 36  timestamp                3297 non-null   object
 37  sp_video_quality         870 non-null    object
 38  sp_download_quality      876 non-null    object
 39  player_video_quality     3005 non-null   object
 40  player_download_quality  988 non-null    object
 41  playbackLanguage         2456 non-null   object
 42  videoQuality             3259 non-null   object
 43  videoQualityPreference   2980 non-null   object
 44  playerVersion            3259 non-null   object
 45  adPlayerVersion          591 non-null    object
 46  companionBanner          287 non-null    object
 47  adPosition               325 non-null    object
 48  adType                   2213 non-null   object
 49  deviceMemory             3163 non-null   object
 50  deviceFreeMemory         2919 non-null   object
 51  deviceCPU                3170 non-null   object
 52  videoType                3186 non-null   object
 53  freePreview              3186 non-null   object
 54  lastGAEvents             2957 non-null   object
 55  statsforNerd             3134 non-null   object
 56  errorType                1708 non-null   object
 57  packName                 3119 non-null   object
 58  playerSource             3037 non-null   object
 59  customLog                0 non-null      float64
 60  timestamp_fe             286 non-null    object
 61  videoSessionId           2865 non-null   object
 62  date                     3297 non-null   datetime64[ns]
 63  time                     3297 non-null   object
 64  timestamp1               3297 non-null   datetime64[ns]
 65  Dates_inserted_at        3297 non-null   object
 66  Time_inserted_at         3297 non-null   object
 67  inserted_at1             3297 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(9), object(56)
memory usage: 1.7+ MB

In [270]:
df['inserted_at'] = df['inserted_at1']

In [271]:
df['timestamp'] = df['timestamp1']

In [272]:
df.to_csv('ins_time_update.csv')

In [274]:
df_new = df

In [275]:
df_new.drop(['date','time','timestamp1','Dates_inserted_at','Time_inserted_at','inserted_at1'],axis=1,inplace=True)

In [276]:
df_new.to_csv('final_data.csv')